### PR TITLE
Capture request Text master2

### PR DESCRIPTION
**Pull request by Yujie1995**
Capture request Write

### CODE REVIEW

**Comment by aseijuy1995** [comment]
Capture request Write from aseijuy1995

**Comment by Yujie1995** [comment]
Capture request Write Yujie1995

**Comment by aseijuy1995** [comment]
- [X]Write the code
- [ ]Write all the tests
- [ ]Document the code

**Comment by aseijuy1995** [comment]
程式片段
‵‵‵java
for(int i = 0 ; i < 5 ; i++){
  System.out.println("i is : " + i);
}
```

**Comment by aseijuy1995** [comment]
引文
> Whether 'tis Nobler in the mind to suffer
> The Slings and Arrows of outrageous Fortune

**Comment by aseijuy1995** [comment]
表情符號
😹

**Comment by aseijuy1995** [comment]
圖片
lines

**Pull request merged**
